### PR TITLE
Loguru

### PR DESCRIPTION
**Pull request by kaylode**
- Use loguru for logging

### CODE REVIEW

**Comment by kaylode** [comment]
@lannguyen0910 , can you test this branch for me? This is just a simple usage while Loguru also has many cool features that I haven't used yet.

**Comment by lannguyen0910** [comment]
> @lannguyen0910 , can you test this branch for me? This is just a simple usage while Loguru also has many cool features that I haven't used yet.

I've tested and the logger worked fine, it logged the same text as the previous one, the difference is it looks prettier and neater, i also notice that once we use some other features of ```Loguru``` it's gonna look more legit than before.

**Comment by kaylode** [comment]
> > @lannguyen0910 , can you test this branch for me? This is just a simple usage while Loguru also has many cool features that I haven't used yet.
> 
> I've tested and the logger worked fine, it logged the same text as the previous one, the difference is it looks prettier and neater, i also notice that once we use some other features of `Loguru` it's gonna look more legit than before.

Ok thank you. Can you revert the fixes in loss functions in this branch and open issues for them. I've tested both the losses and can't reproduce the error, it would be nice if you add the settings to reproduce that.

**Comment by lannguyen0910** [comment]
oh okay, i don't know why i faced those error while testing, i'm gonna revert and open issues if anything is wrong again.

**Comment by lannguyen0910** [comment]
@kaylode i used revert but it didn't change my commits so i hot deleted them, sorry if it annoys you with the unnecessary commits ...

**Comment by kaylode** [comment]
It's fine. Just remember to open a new issue next time

**Pull request merged**
